version: '3'

services:
  web:
    build: .
    # command: gunicorn --bind 0.0.0.0:8000 monitoring.wsgi:application
    command: gunicorn --workers 5 --timeout 120 --bind 0.0.0.0:8000 monitoring.wsgi:application
    volumes:
      - .:/app  # Your Django app code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:  # Reference your .env file
      - .env

  db:
    image: mariadb:10.5  # Use MariaDB image
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  mariadb_data:
  static_volume:
